name: py2
channels:
 - symengine/label/dev
 - conda-forge
 - defaults
dependencies:
 - pexpect
 - pytools
 - conda-forge::numpy
 - conda-forge::sympy
 - python=2.7
 - symengine/label/dev::python-symengine=0.2.0.53.g83912b7=py27_1
 - maxima
